/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvaluacionesRouteImport } from './routes/evaluaciones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PuestosRouteImport } from './routes/puestos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as EvaluacionIdRouteImport } from './routes/evaluacion.$id'
import { Route as RrhhIndexRouteImport } from './routes/rrhh/index'
import { Route as RrhhEvaluacionesRouteImport } from './routes/rrhh/evaluaciones'
import { Route as RrhhRankingRouteImport } from './routes/rrhh/ranking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesRoute = EvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PuestosRoute = PuestosRouteImport.update({
  id: '/puestos',
  path: '/puestos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionIdRoute = EvaluacionIdRouteImport.update({
  id: '/evaluacion/$id',
  path: '/evaluacion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RrhhIndexRoute = RrhhIndexRouteImport.update({
  id: '/rrhh/',
  path: '/rrhh/',
  getParentRoute: () => rootRouteImport,
} as any)
const RrhhEvaluacionesRoute = RrhhEvaluacionesRouteImport.update({
  id: '/rrhh/evaluaciones',
  path: '/rrhh/evaluaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const RrhhRankingRoute = RrhhRankingRouteImport.update({
  id: '/rrhh/ranking',
  path: '/rrhh/ranking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/puestos': typeof PuestosRoute
  '/registro': typeof RegistroRoute
  '/evaluacion/$id': typeof EvaluacionIdRoute
  '/rrhh/evaluaciones': typeof RrhhEvaluacionesRoute
  '/rrhh/ranking': typeof RrhhRankingRoute
  '/rrhh/': typeof RrhhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/puestos': typeof PuestosRoute
  '/registro': typeof RegistroRoute
  '/evaluacion/$id': typeof EvaluacionIdRoute
  '/rrhh/evaluaciones': typeof RrhhEvaluacionesRoute
  '/rrhh/ranking': typeof RrhhRankingRoute
  '/rrhh': typeof RrhhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/puestos': typeof PuestosRoute
  '/registro': typeof RegistroRoute
  '/evaluacion/$id': typeof EvaluacionIdRoute
  '/rrhh/evaluaciones': typeof RrhhEvaluacionesRoute
  '/rrhh/ranking': typeof RrhhRankingRoute
  '/rrhh/': typeof RrhhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/evaluaciones'
    | '/login'
    | '/perfil'
    | '/puestos'
    | '/registro'
    | '/evaluacion/$id'
    | '/rrhh/evaluaciones'
    | '/rrhh/ranking'
    | '/rrhh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/evaluaciones'
    | '/login'
    | '/perfil'
    | '/puestos'
    | '/registro'
    | '/evaluacion/$id'
    | '/rrhh/evaluaciones'
    | '/rrhh/ranking'
    | '/rrhh'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/evaluaciones'
    | '/login'
    | '/perfil'
    | '/puestos'
    | '/registro'
    | '/evaluacion/$id'
    | '/rrhh/evaluaciones'
    | '/rrhh/ranking'
    | '/rrhh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EvaluacionesRoute: typeof EvaluacionesRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PuestosRoute: typeof PuestosRoute
  RegistroRoute: typeof RegistroRoute
  EvaluacionIdRoute: typeof EvaluacionIdRoute
  RrhhEvaluacionesRoute: typeof RrhhEvaluacionesRoute
  RrhhRankingRoute: typeof RrhhRankingRoute
  RrhhIndexRoute: typeof RrhhIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones': {
      id: '/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/evaluaciones'
      preLoaderRoute: typeof EvaluacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puestos': {
      id: '/puestos'
      path: '/puestos'
      fullPath: '/puestos'
      preLoaderRoute: typeof PuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluacion/$id': {
      id: '/evaluacion/$id'
      path: '/evaluacion/$id'
      fullPath: '/evaluacion/$id'
      preLoaderRoute: typeof EvaluacionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rrhh/': {
      id: '/rrhh/'
      path: '/rrhh'
      fullPath: '/rrhh/'
      preLoaderRoute: typeof RrhhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rrhh/evaluaciones': {
      id: '/rrhh/evaluaciones'
      path: '/rrhh/evaluaciones'
      fullPath: '/rrhh/evaluaciones'
      preLoaderRoute: typeof RrhhEvaluacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rrhh/ranking': {
      id: '/rrhh/ranking'
      path: '/rrhh/ranking'
      fullPath: '/rrhh/ranking'
      preLoaderRoute: typeof RrhhRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EvaluacionesRoute: EvaluacionesRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PuestosRoute: PuestosRoute,
  RegistroRoute: RegistroRoute,
  EvaluacionIdRoute: EvaluacionIdRoute,
  RrhhEvaluacionesRoute: RrhhEvaluacionesRoute,
  RrhhRankingRoute: RrhhRankingRoute,
  RrhhIndexRoute: RrhhIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
